# Usar una imagen base de Node.js (versión 18)
FROM node:18

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar package.json y package-lock.json para instalar las dependencias
COPY frontend/package*.json ./

# Limpiar la caché de npm y luego instalar las dependencias
RUN npm cache clean --force
RUN npm install

# Copiar el código fuente del frontend
COPY frontend/ ./

# Instala web-vitals por si falta
RUN npm install web-vitals

# Ejecutar el build de React
RUN npm run build

# Exponer el puerto 3000 (si estás usando ese puerto para la app React)
EXPOSE 3000

# Comando para iniciar la app
CMD ["npm", "start"]